### ISSUE TITLE
Broken Portal Links

### ISSUE THREAD

**Issue by KrystalKane** [cppchriscpp/TravelPortals#23]
Hi again!

Portals work great and are all dandy! Just something happened which is I restarted my server for the server config.txt file to take effect and when I went in to the game, all portals links to each other had broken and then leaving me and friend to relink our portals. Not a massive problem still enjoying plugin!

Was just wondered if this is normal and if this is why you have the /portals export and /portals import command? So when this happens I just reimport the portals etc? 

Kindest regards,

**Comment by Phoenix616** [comment]
What exactly did you change? Can you provide your log and config please?

**Comment by KrystalKane** [comment]
All that happened was I made a texture pack link in my server properties

**Comment by KrystalKane** [comment]
[19:42:02] [Server thread/INFO]: Starting minecraft server version 1.14.4
[19:42:02] [Server thread/INFO]: Loading properties
[19:42:02] [Server thread/WARN]: You specified a resource pack without providing a sha1 hash. Pack will be updated on the client only if you change the name of the pack.
[19:42:02] [Server thread/INFO]: Default game type: SURVIVAL
[19:42:02] [Server thread/INFO]: Generating keypair
[19:42:03] [Server thread/INFO]: Starting Minecraft server on 89.34.96.139:25648
[19:42:03] [Server thread/INFO]: Using epoll channel type
[19:42:05] [Server thread/INFO]: This server is running CraftBukkit version git-Bukkit-e5e8eec (MC: 1.14.4) (Implementing API version 1.14.4-R0.1-SNAPSHOT)
[19:42:14] [Server thread/WARN]: Plugin SetHomes v1.0 does not specify an api-version.
[19:42:15] [Server thread/WARN]: Plugin HealthBar v1.8.3 does not specify an api-version.
[19:42:15] [Server thread/WARN]: Plugin SlimeChunkFinder v1.0 does not specify an api-version.
[19:42:15] [Server thread/INFO]: [SetHomes] Loading SetHomes v1.0
[19:42:15] [Server thread/INFO]: [HealthBar] Loading HealthBar v1.8.3
[19:42:15] [Server thread/INFO]: [BackpacksRemastered] Loading BackpacksRemastered v2019.0.8
[19:42:15] [Server thread/INFO]: [Vault] Loading Vault v1.7.2-b107
[19:42:15] [Server thread/INFO]: [GriefPrevention] Loading GriefPrevention v16.11.6
[19:42:15] [Server thread/INFO]: [LaggRemover] Loading LaggRemover v2.0.6
[19:42:15] [Server thread/INFO]: [SlimeChunkFinder] Loading SlimeChunkFinder v1.0
[19:42:15] [Server thread/INFO]: [TravelPortals] Loading TravelPortals v2.4-SNAPSHOT (build 11)
[19:42:15] [Server thread/INFO]: [VeinMiner] Loading VeinMiner v1.14.0
[19:42:15] [Server thread/INFO]: [DropHeads] Loading DropHeads v3.2.10
[19:42:15] [Server thread/INFO]: [Vault] Enabling Vault v1.7.2-b107
[19:42:15] [Server thread/INFO]: [Vault] [Permission] SuperPermissions loaded as backup permission system.
[19:42:16] [Server thread/INFO]: [Vault] Enabled Version 1.7.2-b107
[19:42:16] [Server thread/WARN]: **** SERVER IS RUNNING IN OFFLINE/INSECURE MODE!
[19:42:16] [Server thread/WARN]: The server will make no attempt to authenticate usernames. Beware.
[19:42:16] [Server thread/WARN]: While this makes the game possible to play without internet access, it also opens up the ability for hackers to connect with any username they choose.
[19:42:16] [Server thread/WARN]: To change this, set "online-mode" to "true" in the server.properties file.
[19:42:16] [Server thread/INFO]: Preparing level "Island World o1"
[19:42:16] [Server thread/INFO]: Reloading ResourceManager: Default, bukkit
[19:42:18] [Server thread/INFO]: Loaded 6 recipes
[19:42:20] [Server thread/INFO]: Preparing start region for dimension 'Island World o1'/minecraft:overworld
[19:42:24] [Server thread/INFO]: Preparing spawn area: 0%
[19:42:24] [Server thread/INFO]: Preparing spawn area: 0%
[19:42:24] [Server thread/INFO]: Preparing spawn area: 0%
[19:42:24] [Server thread/INFO]: Preparing spawn area: 0%
[19:42:24] [Server thread/INFO]: Preparing spawn area: 0%
[19:42:24] [Server thread/INFO]: Preparing spawn area: 0%
[19:42:24] [Server thread/INFO]: Preparing spawn area: 0%
[19:42:24] [Server thread/INFO]: Preparing spawn area: 0%
[19:42:24] [Server thread/INFO]: Preparing spawn area: 0%
[19:42:24] [Server thread/INFO]: Preparing spawn area: 4%
[19:42:25] [Server thread/INFO]: Time elapsed: 5383 ms
[19:42:25] [Server thread/INFO]: Preparing start region for dimension 'Island World o1_nether'/minecraft:the_nether
[19:42:28] [Server thread/INFO]: Preparing spawn area: 0%
[19:42:28] [Server thread/INFO]: Preparing spawn area: 0%
[19:42:28] [Server thread/INFO]: Preparing spawn area: 0%
[19:42:28] [Server thread/INFO]: Preparing spawn area: 0%
[19:42:28] [Server thread/INFO]: Preparing spawn area: 0%
[19:42:28] [Server-Worker-6/INFO]: Preparing spawn area: 83%
[19:42:28] [Server-Worker-6/INFO]: Preparing spawn area: 83%
[19:42:29] [Server-Worker-7/INFO]: Preparing spawn area: 83%
[19:42:29] [Server-Worker-2/INFO]: Preparing spawn area: 83%
[19:42:30] [Server-Worker-2/INFO]: Preparing spawn area: 83%
[19:42:30] [Server-Worker-1/INFO]: Preparing spawn area: 84%
[19:42:31] [Server-Worker-3/INFO]: Preparing spawn area: 86%
[19:42:31] [Server-Worker-6/INFO]: Preparing spawn area: 88%
[19:42:32] [Server thread/INFO]: Time elapsed: 6438 ms
[19:42:32] [Server thread/INFO]: [SetHomes] Enabling SetHomes v1.0
[19:42:32] [Server thread/INFO]: [HealthBar] Enabling HealthBar v1.8.3
[19:42:32] [Server thread/INFO]: [BackpacksRemastered] Enabling BackpacksRemastered v2019.0.8
[19:42:32] [Server thread/INFO]: [BackpacksRemastered] Detected NMS v1_14_R1. Using this for all NMS related functions.
[19:42:36] [Server thread/INFO]: [BackpacksRemastered] BackpacksRemastered v2019.0.8 (git: 61de674) was enabled in 4.15s!
[19:42:36] [Server thread/INFO]: [GriefPrevention] Enabling GriefPrevention v16.11.6
[19:42:36] [Server thread/INFO]: [GriefPrevention] Finished loading configuration.
[19:42:36] [Server thread/INFO]: [GriefPrevention] 9 total claims loaded.
[19:42:38] [Server thread/INFO]: [GriefPrevention] Customizable messages loaded.
[19:42:38] [Server thread/INFO]: [GriefPrevention] Finished loading data (File Mode).
[19:42:38] [Server thread/INFO]: [GriefPrevention] Boot finished.
[19:42:38] [Server thread/INFO]: [LaggRemover] Enabling LaggRemover v2.0.6
[19:42:38] [Server thread/INFO]: 
    __                      ____                                         _    _____
   / /   ____ _____ _____ _/ __ \___  ____ ___  ____ _   _____  _____   | |  / /__ \
  / /   / __ `/ __ `/ __ `/ /_/ / _ \/ __ `__ \/ __ \ | / / _ \/ ___/   | | / /__/ /
 / /___/ /_/ / /_/ / /_/ / _, _/  __/ / / / / / /_/ / |/ /  __/ /       | |/ // __/
/_____/\__,_/\__, /\__, /_/ |_|\___/_/ /_/ /_/\____/|___/\___/_/        |___//____/
            /____//____/

[19:42:38] [Server thread/INFO]: [LaggRemover] Loaded 0 module(s)
[19:42:38] [Server thread/INFO]: [LaggRemover] The LaggRemover AI is now active!
[19:42:38] [Server thread/INFO]: [LaggRemover] LaggRemover has been enabled!
[19:42:38] [Server thread/INFO]: [SlimeChunkFinder] Enabling SlimeChunkFinder v1.0
[19:42:38] [Server thread/ERROR]: Error occurred while enabling SlimeChunkFinder v1.0 (Is it up to date?)
java.lang.NoSuchMethodError: org.bukkit.enchantments.EnchantmentWrapper.<init>(I)V
	at com.conquestiamc.ultiferrago.SlimeChunkFinder.Utils.EnchantGlow.<init>(EnchantGlow.java:18) ~[?:?]
	at com.conquestiamc.ultiferrago.SlimeChunkFinder.Utils.EnchantGlow.getGlow(EnchantGlow.java:63) ~[?:?]
	at com.conquestiamc.ultiferrago.SlimeChunkFinder.Config.ConfigModule.loadConfig(ConfigModule.java:141) ~[?:?]
	at com.conquestiamc.ultiferrago.SlimeChunkFinder.Config.ConfigModule.<init>(ConfigModule.java:66) ~[?:?]
	at com.conquestiamc.ultiferrago.SlimeChunkFinder.Config.ConfigModule.init(ConfigModule.java:73) ~[?:?]
	at com.conquestiamc.ultiferrago.SlimeChunkFinder.SlimeChunkFinder.enableModules(SlimeChunkFinder.java:40) ~[?:?]
	at com.conquestiamc.ultiferrago.SlimeChunkFinder.SlimeChunkFinder.onEnable(SlimeChunkFinder.java:28) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[minecraft_server.jar:git-Bukkit-e5e8eec]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:344) [minecraft_server.jar:git-Bukkit-e5e8eec]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:416) [minecraft_server.jar:git-Bukkit-e5e8eec]
	at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugin(CraftServer.java:447) [minecraft_server.jar:git-Bukkit-e5e8eec]
	at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugins(CraftServer.java:373) [minecraft_server.jar:git-Bukkit-e5e8eec]
	at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:440) [minecraft_server.jar:git-Bukkit-e5e8eec]
	at net.minecraft.server.v1_14_R1.DedicatedServer.init(DedicatedServer.java:253) [minecraft_server.jar:git-Bukkit-e5e8eec]
	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:753) [minecraft_server.jar:git-Bukkit-e5e8eec]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_222]
[19:42:38] [Server thread/INFO]: [TravelPortals] Enabling TravelPortals v2.4-SNAPSHOT (build 11)
[19:42:38] [Server thread/INFO]: [TravelPortals] Loaded 8 portals!
[19:42:38] [Server thread/INFO]: [TravelPortals] TravelPortals version 2.4-SNAPSHOT (build 11) is enabled!
[19:42:38] [Server thread/INFO]: [VeinMiner] Enabling VeinMiner v1.14.0
[19:42:38] [Server thread/INFO]: [VeinMiner] Registering events
[19:42:38] [Server thread/INFO]: [VeinMiner] Registering commands
[19:42:38] [Server thread/INFO]: [VeinMiner] Enabling Plugin Metrics
[19:42:38] [Server thread/INFO]: [VeinMiner] Thank you for enabling Metrics! I greatly appreciate the use of plugin statistics
[19:42:38] [Server thread/INFO]: [VeinMiner] Loading configuration options to local memory
[19:42:38] [Server thread/INFO]: [VeinMiner] Unknown world found... "WorldName". Ignoring...
[19:42:38] [Server thread/INFO]: [VeinMiner] Performing an update check!
[19:42:38] [Server thread/INFO]: [DropHeads] Enabling DropHeads v3.2.10
[19:42:38] [ForkJoinPool.commonPool-worker-25/INFO]: [VeinMiner] Your version of VeinMiner (1.14.0) is up to date!
[19:42:39] [Server thread/INFO]: Server permissions file permissions.yml is empty, ignoring it
[19:42:39] [Server thread/INFO]: Done (23.134s)! For help, type "help"
[19:42:39] [Server thread/INFO]: Starting GS4 status listener
[19:42:39] [Query Listener #1/INFO]: Query running on 89.34.96.139:28083
[19:42:39] [Craft Scheduler Thread - 1/INFO]: [Vault] Checking for Updates ... 
[19:42:39] [Craft Scheduler Thread - 1/INFO]: [Vault] No new version available

**Comment by Phoenix616** [comment]
Well the plugin loaded 8 portals, did you expect more than that and what does `/portal list` show ingame?

Also seeing as you are using a post 1.13 version can you please try at least the development build 29? The last dev bukkit release/build 11 is pretty old by now and did not have explicit 1.13+ support.
